### ISSUE TITLE
Erroneous dashed bond shown

### ISSUE THREAD

**Issue by baoilleach** [kienerj/pycdxml#16]
Here's part of a structure where the original MOL file has a single dashed line, but the resulting CDXML has an additional dashed line to the acid OH.
![image](https://user-images.githubusercontent.com/45337/200894132-49507e19-b8a5-4cc1-aaa7-4c7860e2ee6b.png)

Looking for the source of the problem, I've had a quick look at the code for _set_end_wedge_display_style but I wasn't sure about the "if b.GetIdx() in bonds" as it seems it might give different results depending on the order in which the bonds are present in the molecule. Wouldn't it be simpler to defer the handling of this until after all of the bonds have been processed with a first pass, and then have a second pass looping over the bonds doing whatever is needed to tidy up?

**Comment by kienerj** [comment]
Can you share the original molecule or one that is causing the issue? Just wondering the error appears in all similar cases ("wedge to acid") or if the rest of the molecule matters.

In general yes I'm sure there are better ways to do it. As far as I remember the core "reasoning" was to be able to build the cdxml sequentially, create each element fully and then move to the next element vs. partial element creation and then finding the element again inside the xml and complete it. This would also mean some kind of mapping that maps from rdkit bond idx to a specific cdxml element.

The reasoning for the whole "crutch" is in the method doc string. Test files would fail to show dashed/wedge bonds without having a "WedgedHashEnd" or "WedgeEnd" set. However I can't reproduce this right now with a basic example that displays properly without a "WedgedHashEnd" .

Anyway will look into this.

**Comment by baoilleach** [comment]
Unfortunately, I can't share this molecule. but I'll try and generate an example. Thanks.

**Comment by baoilleach** [comment]
Thanks @kienerj.

**Comment by baoilleach** [comment]
Just a note to say that I've generated 15 orderings of the same small structure, to see whether there was any problem and it looks fine to me. That is to say, all 15 have a problem before, and all 15 are fixed afterwards (apart from the stereo problem reported in #17).
[testcases.sdf.txt](https://github.com/kienerj/pycdxml/files/9984665/testcases.sdf.txt)
