### ISSUE TITLE
Inverted stereo

### ISSUE THREAD

**Issue by baoilleach** [kienerj/pycdxml#17]
I also noticed the Y coordinates were flipped relative to the MOL, and tried the same fix you've done...and then realised (doh!) the stereo is inverted. Hopefully the fix is straightforward - just swap the hash and wedge bonds.

**Comment by kienerj** [comment]
Ok, now I'm confused. The examples from #16 look all the same? Or what am I missing?

I've done the conversion with the "y flip" and it seems fine:

![image](https://user-images.githubusercontent.com/1567309/201290068-d6cf988e-c89a-47e2-a2c5-60b6bee97e9d.png)

Different example:

![image](https://user-images.githubusercontent.com/1567309/201290858-7809547c-d40b-45e9-bc89-a536b1edd362.png)

**Comment by baoilleach** [comment]
Ah - sorry. I assumed that the stereo was correct before. It has indeed inverted, but it was wrong before and now it's right.
