### ISSUE TITLE
CDX to SDF

### ISSUE THREAD

**Issue by suneelbvs** [kienerj/pycdxml#29]
Hi,

Is it possible to extract CDXML to SDF with text as properties?

Thanks in advance.

**Comment by kienerj** [comment]
Hi Suneel,That is currently not possible. However RDKit itself can now read cdxml files. You need to check if rdkit also reads in Properties (called annotations in cdxml) and if not make an issue.Note that there is a big difference between proper annotations and just some text below a molecule in cdxml. The later will never work eg it doesnt even work in chemdraw itself. If you want to export properties to sdf in chemdraw, you need to annotate the molecules. I hope that clarfies this topic.On Mar 24, 2023 21:26, "Dr. Suneel Kumar BVS" ***@***.***> wrote:
Hi,
Is it possible to extract CDXML to SDF with text as properties?
Thanks in advance.

**Comment by suneelbvs** [comment]
Thank you and kudos to awesome work. It really saves lot of time for compchem. Im planning to share this package on my social network too.
